### ISSUE TITLE
Editor crashes when editing script.

### ISSUE THREAD

**Issue by jayrulez** [xenko3d/xenko#110]
The editor seems to crash constantly when editing scripts.

I start by typing public UIPage...
as soon as I start to type the property name the editor crashes.

```
Application: GameStudio
UserEmail: 
UserMessage: 
XenkoVersion: 3.0.0.3
GameStudioVersion: 4
ThreadName: Main thread
DefaultGraphicProfile: Level_10_0
OpenedAssets: dd73cc2c-f632-4387-9b37-98dac320df05:MainScene (Scene)
4d7fbe74-f6dc-f306-0646-8c39b84fdac3:BattleScript (Script Source Code)
44a4cf64-3848-4e33-8f25-d2ff27542aa9:BattleUI (UI page)

LastActions: * +[Update property Appearance.Clip To Bounds]
    * {AssetContentValueChangeOperation: ClipToBounds = False}
* +[Update property Appearance.Visibility]
    * {AssetContentValueChangeOperation: Visibility(∅ -> *) = Hidden}
* +[Update property Appearance.Visibility]
    * {AssetContentValueChangeOperation: Visibility = Collapsed}
* +[Update property Appearance.Visibility]
    * {AssetContentValueChangeOperation: Visibility = Visible}
* +[Reload game assemblies]
    * {ContentValueChangeOperation: EntityComponentCollection[1] --[1] = }
    * {ContentValueChangeOperation: EntityComponentCollection[2] --[2] = }
    * {ReloadAssembliesOperation}
    * {AnonymousDirtyingOperation}
    * {ContentValueChangeOperation: EntityComponentCollection[2] ++[2] = TurnBasedBattleSim.BasicCameraController}
    * {ContentValueChangeOperation: EntityComponentCollection[1] ++[1] = TurnBasedBattleSim.Game.BattleScript}
    * {AnonymousDirtyingOperation}

CurrentDirectory: C:\Program Files\Xenko
CommandArgs: /LauncherWindowHandle 11274966 C:\Users\Robert Campbell\Desktop\GameDev\Xenko\TurnBasedBattleSim\TurnBasedBattleSim.sln
OsVersion: Microsoft Windows 10 Pro 10.0.17134 x64
ProcessorCount: 4
Exception: TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<GetSyntaxRootAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.AbstractDirectiveTriviaBraceMatcher`5.<FindBracesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.BraceMatchingService.<GetMatchingBracesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.BraceMatchingServiceExtensions.<GetAllMatchingBracesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xenko.Assets.Presentation.AssetEditors.ScriptEditor.SimpleCodeTextEditor.<CaretOnPositionChanged>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xenko.GameStudio.Program.Main()

GPU0.AdapterCompatibility: Intel Corporation
GPU0.AdapterDACType: Internal
GPU0.AdapterRAM: 1073741824
GPU0.Availability: 3
GPU0.Caption: Intel(R) HD Graphics 5500
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1920
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 59
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1080
GPU0.Description: Intel(R) HD Graphics 5500
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20160929000000.000000-000
GPU0.DriverVersion: 20.19.15.4531
GPU0.InfFilename: oem10.inf
GPU0.InfSection: iBDWM_w10
GPU0.InstalledDisplayDrivers: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 50
GPU0.Monochrome: False
GPU0.Name: Intel(R) HD Graphics 5500
GPU0.PNPDeviceID: PCI\VEN_8086&DEV_1616&SUBSYS_06651028&REV_09\3&11583659&0&10
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: DESKTOP-88DQ96D
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1920 x 1080 x 4294967296 colors
GPU0.VideoProcessor: Intel(R) HD Graphics Family
Log: 
```

**Comment by Kryptos-FR** [comment]
Unfortunately, it is not fixed, as the base exception (`OperationCanceledException`) must also be caught.
