### ISSUE TITLE
Xenko.Android.sln crashes Visual Studio when opening solution

### ISSUE THREAD

**Issue by guygodin** [xenko3d/xenko#115]
Hi, very happy to see Xenko 3.0 released! Unfortunately I am unable to open the Android solution with the latest version of Visual Studio Community 2017 (v15.8.0). I am can open and compile Xenko.sln but Visual Studio will crash when opening Xenko.Android.sln (callstack from Event Log):

Perhaps I should report this to Microsoft directly?

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.InvalidDataException
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.GetMSBuildProjectExtensionsPath(Boolean)
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject+<GetPackageSpecAsync>d__27.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject+<GetPackageSpecsAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NuGet.VisualStudio.VsPackageInstallerServices+<GetPackagesPathResolverAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NuGet.VisualStudio.VsPackageInstallerServices+<>c__DisplayClass10_0+<<GetInstalledPackages>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.Threading.Tasks.Task`1<System.__Canon>>, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(EnvDTE.Project)
   at Xamarin.VisualStudio.Shell.ProjectOpenProvider+<OnProjectLoaded>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by guygodin** [comment]
The source of the problem appears to be the **Xenko.Core.Tests** project. Removing it from the solution (by editing the solution file) allows me to open the solution and build successfully.
