### ISSUE TITLE
Build error in Release mode (cannot access the file System.Xml.dll)

### ISSUE THREAD

**Issue by nikserdev** [xenko3d/xenko#127]
in debug mode all good.

1>------ Rebuild All started: Project: MyGame999.Game, Configuration: Release Any CPU ------
1>Patch for assembly [MyGame999.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets(311,2): warning : One or more errors occurred.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xenko.Video". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>MyGame999.Game -> D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Game\bin\Release\net461\MyGame999.Game.dll
1>Done building project "MyGame999.Game.csproj".
1>Patch for assembly [MyGame999.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
1>MyGame999.Game -> D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Game\bin\Release\monoandroid50\MonoAndroid50\MyGame999.Game.dll
2>------ Skipped Rebuild All: Project: MyGame999.Windows, Configuration: Release Any CPU ------
2>Project not selected to build for this solution configuration 
3>------ Rebuild All started: Project: MyGame999.Android, Configuration: Release Android ------
3>D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\Properties\AndroidManifest.xml : warning XA0101: @(Content) build action is not supported
3>  OpenGLES
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets(311,2): warning : One or more errors occurred.
3>  Patch for assembly [MyGame999, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
3>  MyGame999.Android -> D:\Development\Home\Xenko\MyGame999\MyGame999\Bin\Android\Release\MyGame999.dll
3>  info 0,000s: [AssetCompiler] BuildEngine arguments: --disable-auto-compile --project-configuration Release --platform=Android --profile=Android --project-configuration=Release --output-path=D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\obj\Android\Release\MonoAndroid50\assets\data --build-path=D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\..\Cache\data --package-file=D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\..\MyGame999.xkpkg --log-pipe=
3>  info 0,000s: [AssetCompiler] Starting builder.
3>  info 2,500s: [AssetCompiler] Build finished in 817 steps. Command results: 0 succeeded, 817 up-to-date, 0 failed, 0 not triggered due to previous failure.
3>  info 2,500s: [AssetCompiler] Build is successful.
3>  info 2,618s: [AssetCompiler] Generate bundles: Scan assets and their dependencies...
3>  info 2,618s: [AssetCompiler] Generate bundles: Assign assets to bundles...
3>  info 2,810s: [AssetCompiler] Generate bundles: Compress and save bundles to HDD...
3>  info 2,813s: [AssetCompiler] Generate bundles: Tried to load previous 'default' bundle but it was invalid. Deleting it...
3>  info 3,488s: [AssetCompiler] Generate bundles: Done
3>  RunTime 00:00:03.78
3>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
3>  No way to resolve conflict between "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning : Failed to read 'D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\obj\Android\Release\MonoAndroid50\linksrc\System.Xml.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning : System.IO.IOException: The process cannot access the file 'D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\obj\Android\Release\MonoAndroid50\linksrc\System.Xml.dll' because it is being used by another process.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): warning :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018: The "StripEmbeddedLibraries" task failed unexpectedly.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA0009: Error while loading assembly: D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\obj\Android\Release\MonoAndroid50\linksrc\System.Xml.dll ---> System.IO.IOException: The process cannot access the file 'D:\Development\Home\Xenko\MyGame999\MyGame999\MyGame999.Android\obj\Android\Release\MonoAndroid50\linksrc\System.Xml.dll' because it is being used by another process.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    --- End of inner exception stack trace ---
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Xamarin.Android.Tasks.StripEmbeddedLibraries.Execute(DirectoryAssemblyResolver res)
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Xamarin.Android.Tasks.StripEmbeddedLibraries.Execute()
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(496,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 1 succeeded, 1 failed, 1 skipped ==========

**Comment by nikserdev** [comment]
I noticed, when I put in the menu Android Project-> Properties-> AndroidOptions-> Linking to the  "SDK Assembly" or "Sdk and user assemblies", this build error occurs. 
I just want to reduce the size of apk. At now I'm build an empty game project with about 90MB apk :/

**Comment by xen2** [comment]
90MB is definitely huge, we'll have to take a look at why it grew so much.
