### ISSUE TITLE
Cant make a new project

### ISSUE THREAD

**Issue by Freewilly06** [xenko3d/xenko#175]
Error: An exception occurred while generating the template.. Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\LightObserver16\Documents\Xenko Projects\MyFirstGame\MyFirstGame.Game\MyFirstGame.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Xenko.Core.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties)
   at Xenko.Core.Assets.Package.FindAssetsInProject(String projectFullPath, String& nameSpace)
   at Xenko.Core.Assets.Package.FindAssetsInProject(ICollection`1 list, Package package)
   at Xenko.Core.Assets.Package.ListAssetFiles(ILogger log, Package package, Boolean listAssetsInMsbuild, Nullable`1 cancelToken)
   at Xenko.Core.Assets.Package.LoadTemporaryAssets(ILogger log, List`1 assetFiles, Nullable`1 cancelToken, Boolean listAssetsInMsbuild, Func`2 filterFunc)
   at Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.Generate(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0()

I recently downloaded Xenko today, I installed the visual studio plugin along with it before I created my first project. However when everything was done setup and I created my created my project it gave the error at the top. I don't know what exactly is wrong since I did everything that I needed to do, can someone help me with this problem please ?

**Comment by Kryptos-FR** [comment]
@Freewilly06 Could you follow the template when creating a new issue? Especially give details on the version used, your machine configurations etc.

Regarding your issue, it looks like the .net SDK is not installed on your machine.

**Comment by xen2** [comment]
This should be fixed in latest Xenko 3.0.0.7 and 3.1 beta.
Please reopen if you still have the issue after an update.
