### ISSUE TITLE
Error In Build Your Engine

### ISSUE THREAD

**Issue by mikrokode** [xenko3d/xenko#262]
Hi,

Friend, I just a programmer, your engine is just a bit too large and complicated for me. Can you show me the correct way to build and debug your engine? I using Window 10, S 2017 Community version, with 4.6.2 Developments Tools. ASAP>>>>>>>

WONG

**Comment by mikrokode** [comment]
Friends,

After I built all the project, i went to bin and run the exe. 
The Following error shown me,

Error: Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. Manifest file path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\SdkResolvers\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.xml'. SDK resolver path: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll [C:\Users\kiantat.wong\Documents\Xenko Projects\FirstPersonShooter\FirstPersonShooter\FirstPersonShooter.Game\FirstPersonShooter.Game.csproj(0,0)]: Error: Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. Manifest file path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\SdkResolvers\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.xml'. SDK resolver path: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll [C:\Users\kiantat.wong\Documents\Xenko Projects\FirstPersonShooter\FirstPersonShooter\FirstPersonShooter.Game\FirstPersonShooter.Game.csproj(0,0)]: Verbose: Loading Assets from Package [Xenko.xkpkg] [C:\Users\kiantat.wong\Documents\Xenko Projects\FirstPersonShooter\FirstPersonShooter\FirstPersonShooter.Game\FirstPersonShooter.Game.csproj(0,0)]: Info: Upgrading package [FirstPersonShooter] to use [Xenko] from version [3.0.0.1-dev] to [3.0.0.7-dev] will be required [C:\Users\kiantat.wong\Documents\Xenko Projects\FirstPersonShooter\FirstPersonShooter\FirstPersonShooter.Game\FirstPersonShooter.Game.csproj(0,0)]: Warning: Unable to load project [FirstPersonShooter.Game.csproj]. Microsoft.Build.Exceptions.InvalidProjectFileException: Could not load SDK Resolver. A manifest file exists, but the path

Any Idea about this problem?

**Comment by mikrokode** [comment]
Hi,

When I created a new game project, the following error showing up again ,,,,

Verbose: Loading Assets from Package [Xenko.xkpkg]
Verbose: Loading Assets from Package [MyGame2.xkpkg]
Verbose: Generating MyGame2.Game...
Verbose: Generating MyGame2.Windows...
Error: An exception occurred while generating the template.. Microsoft.Build.Exceptions.InvalidProjectFileException: Could not load SDK Resolver. A manifest file exists, but the path to the SDK Resolver DLL file could not be found. Manifest file path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\SdkResolvers\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.xml'. SDK resolver path: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\Microsoft.Build.NuGetSdkResolver.dll  C:\Users\kiantat.wong\Documents\Xenko Projects\MyGame2\MyGame2\MyGame2.Game\MyGame2.Game.csproj
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.TryAddAssemblyFromManifest(String pathToManifest, String manifestFolder, List`1 assembliesList, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.FindPotentialSdkResolvers(String rootFolder, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverLoader.LoadResolvers(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.Initialize(LoggingContext loggingContext, ElementLocation location)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>c__DisplayClass3_0.<ResolveSdk>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName)
   at Xenko.Core.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties)
   at Xenko.Core.Assets.Package.FindAssetsInProject(String projectFullPath, String& nameSpace)
   at Xenko.Core.Assets.Package.FindAssetsInProject(ICollection`1 list, Package package)
   at Xenko.Core.Assets.Package.ListAssetFiles(ILogger log, Package package, Boolean listAssetsInMsbuild, Nullable`1 cancelToken)
   at Xenko.Core.Assets.Package.LoadTemporaryAssets(ILogger log, List`1 assetFiles, Nullable`1 cancelToken, Boolean listAssetsInMsbuild, Func`2 filterFunc)
   at Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.Generate(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0()

**Comment by Kryptos-FR** [comment]
You are missing the .net SDK or some other dependencies.

Please follow the steps to properly install all prerequisites. The README lists all prerequisites and the troubleshooting section of the documentation contains some useful information.

**Comment by mikrokode** [comment]
Friends,

Still same, any other ideas?
