### ISSUE TITLE
Can't install Xenko

### ISSUE THREAD

**Issue by SeaPeaMe** [xenko3d/xenko#310]
Hey everyone, I was having errors when installing Xenko and I have retried a countless amount of times... Here's the error log thing:

An error occurred while installing version 3.1.0.1-beta01-0318.
Failed to retrieve information about 'Xenko.Assets' from remote source 'https://api.nuget.org/v3-flatcontainer/xenko.assets/index.json'.
Value cannot be null. Parameter name: packageDownloader at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.ProjectRestoreCommand.<InstallPackageAsync>d13.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.ProjectRestoreCommand.<>cDisplayClass12_1.<<InstallPackagesAsync>b2>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.ProjectRestoreCommand.<InstallPackagesAsync>d12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.ProjectRestoreCommand.<TryRestoreAsync>d8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d47.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.RestoreCommand.<ExecuteAsync>d32.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.Core.Packages.NugetStore.<InstallPackage>d__50.MoveNext() --- End of stack trace from previous location where exception was thrown ---

Could you guys please help? Xenko looks like a cool game engine

**Comment by SeaPeaMe** [comment]
Yeah, I get that Json data. And I just tried installing it again and got a different error:

An error occurred while installing version 3.1.0.1-beta01-0318.
Failed to download package 'Xenko.Core.BuildEngine.Common.3.1.0.1-beta01-0318' from 'https://api.nuget.org/v3-flatcontainer/xenko.core.buildengine.common/3.1.0.1-beta01-0318/xenko.core.buildengine.common.3.1.0.1-beta01-0318.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xenko.core.buildengine.common/3.1.0.1-beta01-0318/xenko.core.buildengine.common.3.1.0.1-beta01-0318.nupkg' has timed out after 100000ms.
Unable to find package 'AvalonEdit.5.0.2'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()
 
And my internet is working fine. I can go on the web and watch Youtube, etc.

**Comment by Kryptos-FR** [comment]
Looks more and more like a network issue. There could be lots of reason why this happens: antivirus filtering/scanning that slows down the download, restrictions at the internet provider level, specific routing issues in your area, server cache issues at nuget level, a combination of the aforementioned...

Not much we can do on our end unfortunately. @xen2 can we increase the timeout or add more retries. Also wondering if the version of the nuget client could be a factor (do we make sure it is installed with the prerequisites?).

**Comment by SeaPeaMe** [comment]
K, well I guess I'll try later on. Thanks for your help

**Comment by SleepyMode** [comment]
Any update on this? @SeaPeaMe

**Comment by SeaPeaMe** [comment]
Ah, yes. I'm so sorry! I haven't been around to reply.

Yep! I tried a few days later and I downloaded Xenko successfully!

**Comment by 3DRaddict** [comment]
![xenco_install_error](https://user-images.githubusercontent.com/8180184/51424487-30abe100-1bd7-11e9-851f-b1475968d16c.jpg)
On installing v3.1 I get the above error
I was able to install and run v3.0 on both Windows 7 and Windows 10
I've uninstalled  and attempted installation of v3.1 a number of times since the first issue of v3.1 always with the above error appearing after a few minutes of the installation process,

**Comment by SeaPeaMe** [comment]
Yeah, @3DRaddict, I don't know why this happened. I just notified the Xenko devs and they fixed it eventually

**Comment by xen2** [comment]
@3DRaddict Do you still have the issue?

**Comment by 3DRaddict** [comment]
Yes.....on both Windows 7 and Windows 10, on seperate machines.....

An error occurred while installing version 3.1.0.1-beta01-0406.
Failed to retrieve information about 'Microsoft.Build' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.build/index.json'.
Unable to find package 'RoslynPad.Editor.Windows.1.0.4'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()

**Comment by Kryptos-FR** [comment]
Issue at nuget level. @xen2 I think it's time to report those to nuget team. Seems like something is wrong on their end.

**Comment by dfkeenan** [comment]
Hi,

I am getting a similar error "Unable to find package 'Xenko.Core.Yaml.3.1.0.1-beta01-0406'".:

An error occurred while installing version 3.1.0.1-beta01-0406.
Failed to download package 'Xenko.Core.Yaml.3.1.0.1-beta01-0406' from 'https://api.nuget.org/v3-flatcontainer/xenko.core.yaml/3.1.0.1-beta01-0406/xenko.core.yaml.3.1.0.1-beta01-0406.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/xenko.core.yaml/3.1.0.1-beta01-0406/xenko.core.yaml.3.1.0.1-beta01-0406.nupkg' has timed out after 100000ms.
Unable to find package 'Xenko.Core.Yaml.3.1.0.1-beta01-0406'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()

**Comment by LanceJZ** [comment]
I'm having the same issues.

**Comment by xen2** [comment]
Can someone having the issue please try again with latest launcher 3.0.7?
It should display the full nuget log.
Thanks!

**Comment by xen2** [comment]
Attaching log from discord:
[XenkoLauncherLog.txt](https://github.com/xenko3d/xenko/files/3163013/XenkoLauncherLog.txt)

**Comment by dfkeenan** [comment]
I got this on trying to update to 3.0.09:
```
An error occurred while installing version 3.0.0.9.
Log

[21:05:46] Info:   GET https://api.nuget.org/v3/registration3-gz-semver2/xenko.launcher/index.json
[21:05:46] Info:   GET https://api.nuget.org/v3/registration3-gz-semver2/xenko.gamestudio/index.json
[21:05:47] Info:   OK https://api.nuget.org/v3/registration3-gz-semver2/xenko.launcher/index.json 942ms
[21:05:47] Info:   OK https://api.nuget.org/v3/registration3-gz-semver2/xenko.gamestudio/index.json 1211ms
[21:05:49] Info:   GET https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko.GameStudio'&semVerLevel=2.0.0
[21:05:49] Info:   GET https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko.Launcher'&semVerLevel=2.0.0
[21:05:49] Info:   OK https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko.GameStudio'&semVerLevel=2.0.0 233ms
[21:05:50] Info:   OK https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko.Launcher'&semVerLevel=2.0.0 828ms
[21:05:51] Info:   GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko.Launcher'&semVerLevel=2.0.0
[21:05:51] Info:   GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko.GameStudio'&semVerLevel=2.0.0
[21:05:51] Info:   OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko.GameStudio'&semVerLevel=2.0.0 332ms
[21:05:52] Info:   OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko.Launcher'&semVerLevel=2.0.0 1291ms
[21:05:52] Info:   GET https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko.GameStudio'&semVerLevel=2.0.0
[21:05:52] Info:   GET https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko.Launcher'&semVerLevel=2.0.0
[21:05:53] Info:   OK https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko.GameStudio'&semVerLevel=2.0.0 425ms
[21:05:53] Info:   GET https://api.nuget.org/v3/registration3-gz-semver2/xenko/index.json
[21:05:54] Info:   OK https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko.Launcher'&semVerLevel=2.0.0 1281ms
[21:05:54] Info:   OK https://api.nuget.org/v3/registration3-gz-semver2/xenko/index.json 1036ms
[21:05:54] Info:   GET https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:05:58] Info:   OK https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 4032ms
[21:05:58] Info:   GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:05:58] Info:   OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 359ms
[21:05:58] Info:   GET https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:05:59] Info:   OK https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 335ms
[21:05:59] Info:   GET https://api.nuget.org/v3/registration3-gz-semver2/xenko.visualstudio.package/index.json
[21:06:00] Info:   OK https://api.nuget.org/v3/registration3-gz-semver2/xenko.visualstudio.package/index.json 949ms
[21:06:00] Info:   GET https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko.VisualStudio.Package'&semVerLevel=2.0.0
[21:06:00] Info:   OK https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko.VisualStudio.Package'&semVerLevel=2.0.0 238ms
[21:06:00] Info:   GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko.VisualStudio.Package'&semVerLevel=2.0.0
[21:06:00] Info:   OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko.VisualStudio.Package'&semVerLevel=2.0.0 328ms
[21:06:00] Info:   GET https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko.VisualStudio.Package'&semVerLevel=2.0.0
[21:06:01] Info:   OK https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko.VisualStudio.Package'&semVerLevel=2.0.0 328ms
[21:06:06] Minimal: Restoring packages for XenkoLauncher.json...
[21:06:06] Verbose: Restoring packages for .NETFramework,Version=v4.7.2...
[21:06:06] Info:   GET https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:06:06] Info:   GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:06:06] Info:   GET https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:06:07] Info:   OK https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 299ms
[21:06:07] Info:   GET https://packages.xenko.com/api/v2/package/xenko/3.0.0.9
[21:06:07] Info:   OK https://packages.xenko.com/api/v2/package/xenko/3.0.0.9 26ms
[21:06:07] Info:   GET https://api.nuget.org/v3-flatcontainer/xenko/index.json
[21:06:08] Info:   OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 1322ms
[21:06:08] Info:   OK https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 1459ms
[21:06:08] Info:   OK https://api.nuget.org/v3-flatcontainer/xenko/index.json 1187ms
[21:06:16] Minimal: Failed to download package 'Xenko.3.0.0.9' from 'https://packages.xenko.com/api/v2/package/xenko/3.0.0.9'.
Received an unexpected EOF or 0 bytes from the transport stream.
[21:06:16] Info:   GET https://packages.xenko.com/api/v2/package/xenko/3.0.0.9
[21:06:16] Info:   OK https://packages.xenko.com/api/v2/package/xenko/3.0.0.9 79ms
[21:06:31] Minimal: Failed to download package 'Xenko.3.0.0.9' from 'https://packages.xenko.com/api/v2/package/xenko/3.0.0.9'.
Received an unexpected EOF or 0 bytes from the transport stream.
[21:06:31] Info:   GET https://packages.xenko.com/api/v2/package/xenko/3.0.0.9
[21:06:31] Info:   OK https://packages.xenko.com/api/v2/package/xenko/3.0.0.9 80ms
[21:07:14] Error: Failed to download package 'Xenko.3.0.0.9' from 'https://packages.xenko.com/api/v2/package/xenko/3.0.0.9'.
Received an unexpected EOF or 0 bytes from the transport stream.
[21:07:14] Info:   GET https://api.nuget.org/v3-flatcontainer/xenko/index.json
[21:07:14] Info:   GET https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:07:14] Info:   GET https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:07:14] Info:   GET https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:07:14] Info:   OK https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 316ms
[21:07:14] Info:   OK https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 330ms
[21:07:14] Info:   OK https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0 332ms
[21:07:14] Info:   CACHE https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:07:14] Info:   CACHE https://www.myget.org/F/xamlbehaviors-nightly/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:07:14] Info:   CACHE https://packages.xenko.com/nuget/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0
[21:07:14] Info:   CACHE https://www.myget.org/F/avalonia-ci/api/v2/FindPackagesById()?id='Xenko'&semVerLevel=2.0.0

Exception

Unable to find package 'Xenko.3.0.0.9'.
   at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.RemoteV2FindPackageByIdResource.<GetDependencyInfoAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass21_0.<<GetDependenciesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d__1.MoveNext()

```

**Comment by mostafa901** [comment]
I am facing a similar scenario.. I have a Window App Targeting 4.7.2, and by adding nuget Xenko.Engine I get this Error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Xenko.Core.IO 3.1.0.1-beta02-0752'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

```
Do i miss installation of any additional framework library??!!
