### ISSUE TITLE
Adding shader to game project throws exception

### ISSUE THREAD

**Issue by tebjan** [xenko3d/xenko#324]
**Release Type**: Official Release/GitHub (please choose appropriate option)
official
**Version**: Version number and/or git branch
beta1-359
**Platform(s)**: Does the problem occur on Windows, Android...?
shared
**Describe the bug**
adding an .xksl file to the project throws exception (Xenko.Core, Version=3.1.0.1 not found) and gives red file in project

**To Reproduce**
add empty or existing .xksl file to game project

**Expected behavior**
shader keys should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/1094716/51128593-89baf400-1828-11e9-8909-1d10c58a9c5e.png)

**Log and callstacks**
[ShaderKeyGenStackTrace.txt](https://github.com/xenko3d/xenko/files/2756266/ShaderKeyGenStackTrace.txt)

**Additional context**
trying to build a re-usable xenko package, but also happens in new empty game project.

**Comment by Kryptos-FR** [comment]
Looks like it is missing the tool option to generate the corresponding `.cs` file.

**Comment by tebjan** [comment]
looking at the stack trace, the key gen tool seems to get called, but then doesn't find a specific reference:
   at Xenko.Core.DataSerializers.Xenko_Core_ShadersSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Xenko.VisualStudio.Commands.Shaders.ShaderKeyFileHelper.GenerateCode(String inputFileName, String inputFileContent)

**Comment by xen2** [comment]
I think I simply need to release a new VSPackage due to change to this line:
https://github.com/xenko3d/xenko/blob/master/sources/shared/Xenko.NuGetResolver/RestoreHelper.cs#L32
I will test if that fixes it.

Thanks for the report.

**Comment by tebjan** [comment]
another thing i noticed, we have a quite special nuget that brings many files into the .csproj via its content folder that also triggers the keygen tool. not sure how this should be defined. i can send you the nuget to test, if you are interested. 
![image](https://user-images.githubusercontent.com/1094716/51428840-b98f4080-1c08-11e9-8970-58fd584497b0.png)
