### ISSUE TITLE
Reinstall fails on Win8.1 following uninstall via setup.

### ISSUE THREAD

**Issue by aurodev** [xenko3d/xenko#338]
**Release Type:**
Official

**Version:**
3.0.0.6 Official
3.1 Beta Official
Launcher 3.0.5

**Platform(s):**
Windows 8.1

**System**
OS/device including version:
Windows 8.1 64bit, 8GB AMD FX 6350 6 core
.NET framework installed as of 1.21.19 .NET 4.7.2 Reg key: Release REG_DWORD 461814
Nuget 4.92 

Graphics Chipset
AMD Radeon HD 7700 Series
Memory Size 1024 MB
Radeon Software Version 17.4.4

**Describe the bug**
For us an uninstall-Reinstall of Xenko and the launcher resulted in:

1) Local dev copy of Xenko 3.0.0.6 that was previously building and working exits with an invalid operation in mscorlib under debug in VS2017, built but would not run. XenkoGameStudio.exe shows in the process list but shuts down without window display.

2) Clean reinstall (multiple times) of the Xenko launcher v.3.0.5 and attempted install of 3.0.0.6 or 3.1beta presents with the error shown in the launcher screenshot and below.

**To Reproduce**
1. Download the launcher and attempt to install Xenko following an uninstall of Xenko (3.0.0.6 and 3.1 beta) 

**Expected behavior**
A proper install without errors.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![image](https://user-images.githubusercontent.com/7356383/51562394-c190ef80-1e57-11e9-8def-4f1fbbefb01a.png)

**Log and callstacks**
If any, please attach here any log or callstack (preferably in a `.txt` file using GitHub drag and drop)

```
An error occurred while installing version 3.0.0.6.
Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
 at System.IO.Compression.ZipArchive.ReadCentralDirectory()
 at System.IO.Compression.ZipArchive.get_Entries()
 at NuGet.Packaging.ZipArchiveExtensions.GetFiles(ZipArchive zipArchive)
 at NuGet.Protocol.LocalV2FindPackageByIdResource.GetPackageInfosCore(String id, ILogger logger)
 at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
 at NuGet.Protocol.LocalV2FindPackageByIdResource.GetPackageInfos(String id, SourceCacheContext cacheContext, ILogger logger)
 at NuGet.Protocol.LocalV2FindPackageByIdResource.GetAllVersionsAsync(String id, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<GetAllVersionsAsync>d28.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryCoreAsync>d20.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass19_0.<<FindLibraryAsync>b0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<FindLibraryAsync>d19.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.DependencyResolver.ResolverUtility.<>cDisplayClass7_1.<<FindLibraryFromSourcesAsync>b0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.DependencyResolver.ResolverUtility.<FindLibraryFromSourcesAsync>d7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Additional context**
Googling the error "Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory." shows similar issues with downloading/uploading zip files.

**Comment by Kryptos-FR** [comment]
Could you give us the list of nuget package sources currently existing and activated?

In Visual Studio, go to **Tools > Options** command and scroll to **NuGet Package Manager**, then select **Package Sources**.

**Comment by aurodev** [comment]
Package sources
![image](https://user-images.githubusercontent.com/7356383/51577957-b48cf400-1e89-11e9-80ba-bc3e2dfe5384.png)


Also the latest master does build, after waiting 5 min as DiegoBM suggested but when XenkoGameStudio.exe is run a dialog box pops up that then automatically opens a text editor with a similar central directory error.

![image](https://user-images.githubusercontent.com/7356383/51578146-8cea5b80-1e8a-11e9-80bf-64dff744a018.png)


[nuget_error.txt](https://github.com/xenko3d/xenko/files/2785377/nuget_error.txt)

**Comment by aurodev** [comment]
Even with a fresh reinstall of the launcher it seems to still end up with these errors.

**Comment by xen2** [comment]
What happens if you delete xenko\xenko (4th source)? (not only uncheck but delete with X button)
If not enough, pleas do that also with xenko (5th source) and then xenko dev (3rd source)

**Comment by aurodev** [comment]
A little early... 

**You were right. Deleting the 3 local sources worked.** 
![image](https://user-images.githubusercontent.com/7356383/51582296-68e24680-1e99-11e9-949a-3eb98d2f605c.png)
![image](https://user-images.githubusercontent.com/7356383/51582327-8e6f5000-1e99-11e9-9ec8-34ab55648121.png)


Will try reinstalling the launcher tomorrow.

**Comment by xen2** [comment]
OK thanks for the update!
I will think about automatically purging non-existant Xenko feeds automatically.

**Comment by aurodev** [comment]
Launcher and GameStudio now behave normally.


![image](https://user-images.githubusercontent.com/7356383/51614840-7f69bb80-1ef4-11e9-894b-f28113af0325.png)
![launcherreinstall](https://user-images.githubusercontent.com/7356383/51614860-855f9c80-1ef4-11e9-8bc7-fd6eda80d050.PNG)

**Comment by xen2** [comment]
I will reopen to do the following improvement on Xenko side:
When Xenko or Xenko Launcher is started, check all Xenko package sources and delete the ones for which folder doesn't exist anymore.
