### ISSUE TITLE
Create "New Game" fails.

### ISSUE THREAD

**Issue by mockc** [xenko3d/xenko#405]
**Release Type**: Official Release

**Version**: 3.1.0.1-beta02-0527

**Platform(s)**: Windows 10 x64

**Describe the bug**
Attempting to create a new game using the "New Game" template generates the following error.
"Error:An exception occurred while generating the template."

**To Reproduce**
1. Start Game Studio
2. Select "New Game"
3. Click "Select"
4. Click "Ok"

**Expected behavior**
Should create a new game with the basic scene.

**Screenshots**
N/A

**Log and callstacks**
Error:An exception occurred while generating the template.
Object reference not set to an instance of an object.
   at Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.CopyAssetPacks(SessionTemplateGeneratorParameters parameters, Package package)
   at Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.Generate(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0()

**Additional context**
I installed the prerequisites and pulled the repo to try and debug the problem. However, the solution fails to compile, complaining that clang is not compatible. I ensured git lfs was installed per another issue that came up in a google search.

**Comment by xen2** [comment]
Fixed with 8227cfdb4
