### ISSUE TITLE
Samples Crashing (SharpDX.SharpDXException)

### ISSUE THREAD

**Issue by RhysUCP** [xenko3d/xenko#459]
**Release Type**: Official Release

**Version**: 3.0 and 3.1

**Platform(s)**: Windows

**Describe the bug**
Unable to run the sample projects, such as simple audio, JumpyJet, Space Escape etc. After creating a new project with these samples, I press the build and start game then a console appears with red text and an error saying the program has stopped working. The error is shown as "Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070
057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The
 parameter is incorrect."

**To Reproduce**
1. Downloaded and installed latest version
2. Created a new project using the samples
3. Build and run project

**Expected behavior**
Expecting the sample to run and be usable.

**Screenshots**
![1](https://user-images.githubusercontent.com/32268193/58443980-9829ee00-80ed-11e9-84e9-16e23eaca772.png)
![2](https://user-images.githubusercontent.com/32268193/58443978-97915780-80ed-11e9-8eec-33692810c0b2.png)

**Log and callstacks**
[visual_studio.txt](https://github.com/xenko3d/xenko/files/3225252/visual_studio.txt)
[console.txt](https://github.com/xenko3d/xenko/files/3225253/console.txt)

**Additional context**
Templates are working.
Tested on version 3.0 and 3.1.
Using Windows 7 and GeForce GTX 900 series.

**Comment by Kryptos-FR** [comment]
I had a similar issue that disappeared once I updated my drivers (also Nvidia card).
What is the version of your driver package?

**Comment by RhysUCP** [comment]
I read elsewhere too that updating drivers may fix the issue, so I did a clean install for the latest NVIDIA driver (430.86) but the problem still persists. This shows as version 26.21.14.3086 in device manager.

**Comment by coruscateor** [comment]
I am currently having this problem with SimpleAudio, JumpyJet and SpaceEscape on an
AMD Radeon RX 580 using the 19.9.2 drivers (latest/stable as of this writing).

I am also on Windows 7 and using the stable 3.1 version of the engine.

**Comment by Basewq** [comment]
I've had the same issue.
The problem seems to be Default Graphics Profile set to Direct3D 9.3 (and possibly lower) in the GameSettings -> Rendering section.
If you change it to 10.0 or higher, the SharpDX error goes away.

**Comment by Basewq** [comment]
Enabling debug logging shows the following error:
```
D3D11 WARNING: ID3D11DeviceContext1::SetPrivateData: Existing private data of same name with different size found! [ STATE_SETTING WARNING #55: SETPRIVATEDATA_CHANGINGPARAMS]
D3D11 ERROR: ID3D11Device::CreateQuery: CreateQuery: EVENT and OCCLUSION queries are not available at this feature level. [ STATE_CREATION ERROR #232: CREATEQUERYORPREDICATE_INVALIDQUERY]
Exception thrown at 0x000007FEFCFFA06D in GameMenu.Windows.exe: Microsoft C++ exception: _com_error at memory location 0x000000000039E060.
Exception thrown: 'SharpDX.SharpDXException' in SharpDX.dll
'GameMenu.Windows.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll'. 
[Game]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateQuery(QueryDescription queryDescRef, Query queryOut)
   at SharpDX.Direct3D11.Query..ctor(Device device, QueryDescription description)
   at Xenko.Graphics.GraphicsDevice.Begin()
   at Xenko.Games.GraphicsDeviceManager.Xenko.Games.IGraphicsDeviceManager.BeginDraw()
   at Xenko.Games.GameBase.BeginDraw()
   at Xenko.Games.GameBase.InitializeBeforeRun()
[Game]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateQuery(QueryDescription queryDescRef, Query queryOut)
   at SharpDX.Direct3D11.Query..ctor(Device device, QueryDescription description)
   at Xenko.Graphics.GraphicsDevice.Begin()
   at Xenko.Games.GraphicsDeviceManager.Xenko.Games.IGraphicsDeviceManager.BeginDraw()
   at Xenko.Games.GameBase.BeginDraw()
   at Xenko.Games.GameBase.InitializeBeforeRun()
Exception thrown: 'SharpDX.SharpDXException' in Xenko.Games.dll
An unhandled exception of type 'SharpDX.SharpDXException' occurred in Xenko.Games.dll
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
```

The following steps increases the debug logging to show the above error:
1. Right click the Windows project -> Properties -> Debug
2. Tick `Enable native code debugging`
3. Set `DeviceCreationFlags.Debug` on the `GraphicsDeviceManager`, ie.
```
using (var game = new Game())
{
    game.GraphicsDeviceManager.DeviceCreationFlags = Xenko.Graphics.DeviceCreationFlags.Debug;
    game.Run();
}
```

**Comment by AmbulantRex** [comment]
I'm seeing this same error when trying to load the VR sample using the Valve Index. I'm not sure if it happens with other headsets. 

After running with the debug flag, I receive this additional information:

```
D3D11 ERROR: ID3D11Device::CreateShaderResourceView: The Format (0x1b, R8G8B8A8_TYPELESS) is invalid, when creating a View; it is not a fully qualified Format castable from the Format of the Resource (0x1b, R8G8B8A8_TYPELESS). [ STATE_CREATION ERROR #127: CREATESHADERRESOURCEVIEW_INVALIDFORMAT]
D3D11 ERROR: ID3D11Device::CreateShaderResourceView: The format (0x1b, R8G8B8A8_TYPELESS) cannot be used with a ShaderResource view. [ STATE_CREATION ERROR #127: CREATESHADERRESOURCEVIEW_INVALIDFORMAT]
Exception thrown at 0x00007FFFBD3F3E49 in GameApp.Windows.exe: Microsoft C++ exception: _com_error at memory location 0x000000876617BFA0.
D3D11 ERROR: ID3D11Device::CreateShaderResourceView: Returning E_INVALIDARG, meaning invalid parameters were passed. [ STATE_CREATION ERROR #131: CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN]
```

I appears to be using the R8G8B8A8_Typeless defined in PixelFormat.cs in Stride.Graphics. It also occurs primarily while loading the Mirror texture specifically here:

https://github.com/stride3d/stride/blob/273dfddd462fd3746569f833e1493700c070b14d/sources/engine/Stride.VirtualReality/OpenVR/OpenVrHmd.cs#L53

I don't understand D3D11 well enough to do more than guess at the problem at this time.

**Comment by xen2** [comment]
@AmbulantRex does it still happen if you set Default Graphics Profile to Direct3D 10.0 or higher?

**Comment by AmbulantRex** [comment]
@xen2 It does. I'm currently using 11.

![image](https://user-images.githubusercontent.com/21176662/100759653-184da580-33ae-11eb-8c17-681e6176b109.png)

**Comment by FyiurAmron** [comment]
> I've had the same issue. The problem seems to be Default Graphics Profile set to Direct3D 9.3 (and possibly lower) in the GameSettings -> Rendering section. If you change it to 10.0 or higher, the SharpDX error goes away.

I can repro, this is also exactly what happens for me (Windows 7 64-bit, most up-to-date drivers for Radeon RX 580).

> @AmbulantRex does it still happen if you set Default Graphics Profile to Direct3D 10.0 or higher?

For me, any profile >= 10.0 (up until 11.0 included) works correctly, and any <= 9.3 breaks with exactly the "The parameter is incorrect" error (as described by OP).

**Comment by Eideren** [comment]
Closing this as outdated, graphics back-end has had significant amount of changes since then.
FyiurAmron's issue is #2269
