### ISSUE TITLE
Game Studio Crashes when changing value of canvas under layout tab properties

### ISSUE THREAD

**Issue by DwiYI** [xenko3d/xenko#532]
**Release Type**: Official Release/GitHub

**Version**: 3.1.0.1-beta02

**Describe the bug**
When changing value of Canvas. 

**To Reproduce**
1. Open UI Page
2. Add Canvas, Add Child of Canvas
3. Change value Canvas Under Layout tab properties

**Expected behavior**
It should not Crash

**Screenshots**
![crash](https://user-images.githubusercontent.com/19425248/67158168-f38b9f80-f35e-11e9-9c5c-37a673188e4e.png)

**Comment by phr00t** [comment]
Couldn't get this to crash on my fork...

**Comment by Eideren** [comment]
I can't reproduce it either, could you attach the logs ?

**Comment by DwiYI** [comment]
this below log from game studio crash :
 
```Application: GameStudio
UserEmail: 
UserMessage: 
XenkoVersion: 3.2.0.1-beta01
GameStudioVersion: 4
ThreadName: Main thread
CrashLocation: 0
ProcessID: 17400
DefaultGraphicProfile: Level_9_3
OpenedAssets: f092b2aa-b4c0-44c7-9747-45f5b9bc3824:SplashScene (Scene)
81c99575-eda0-490e-b8b2-03a2490cd5ee:Page (UI page)

LastActions: * +[Add 1 element to [Canvas]]
    * {AssetContentValueChangeOperation: AssetPartCollection`2 ++[2bb1bb00-c997-47a6-96cb-5a07787f66a5] = UIElementDesign [ImageElement, ]}
    * {AssetContentValueChangeOperation: UIElementCollection ++[0] = Xenko.UI.Controls.ImageElement}
* +[Update property Layout.Maximum Depth]
    * {AssetContentValueChangeOperation: MaximumDepth = 3.402823E+38}
* +[Update property Layout.Maximum Height]
    * {AssetContentValueChangeOperation: MaximumHeight = 3.402823E+38}
* +[Update property Layout.Maximum Width]
    * {AssetContentValueChangeOperation: MaximumWidth = 3.402823E+38}
* +[Xenko.Core.Transactions.Transaction]
    * {AssetContentValueChangeOperation: PropertyContainerClass ++[AbsolutePositionPropertyKey] = X:1 Y:0 Z:0}

CurrentDirectory: G:\Xenko 3.2\sources\editor\Xenko.GameStudio\bin\Debug\net472
CommandArgs: 
OsVersion: Microsoft Windows 10 Pro 10.0.18363 x64
ProcessorCount: 16
Exception: TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.SetValue(Object item, Object value)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xenko.GameStudio.DataBindingExceptionRethrower.ThrowIfExceptionInSetter(TraceEventType eventType, Int32 id)
   at Xenko.GameStudio.DataBindingExceptionRethrower.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
   at MS.Internal.TraceData.Trace(TraceEventType type, AvTraceDetails traceDetails, Object p1, Object p2)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
   at System.Windows.Data.BindingExpressionBase.UpdateValue()
   at System.Windows.Data.BindingExpressionBase.ProcessDirty()
   at System.Windows.Data.BindingExpressionBase.Dirty()
   at System.Windows.Data.BindingExpressionBase.SetValue(DependencyObject d, DependencyProperty dp, Object value)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at MS.Internal.Data.PropertyPathWorker.SetValue(Object item, Object value)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xenko.GameStudio.DataBindingExceptionRethrower.ThrowIfExceptionInSetter(TraceEventType eventType, Int32 id)
   at Xenko.GameStudio.DataBindingExceptionRethrower.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
   at MS.Internal.TraceData.Trace(TraceEventType type, AvTraceDetails traceDetails, Object p1, Object p2)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
   at System.Windows.Data.BindingExpressionBase.UpdateValue()
   at Xenko.Core.Presentation.Controls.NumericTextBox.OnValidated()
   at Xenko.Core.Presentation.Controls.TextBoxBase.Validate()
   at Xenko.Core.Presentation.Controls.TextBoxBase.OnPreviewKeyDown(KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xenko.GameStudio.Program.Main()

InnerException:
  NodePresenterException: An error occurred while updating the value of the node, see the inner exception for more information.
     at Xenko.Core.Presentation.Quantum.Presenters.VirtualNodePresenter.UpdateValue(Object newValue)
     at Xenko.Core.Presentation.Quantum.ViewModels.NodeViewModel.SetNodeValue(Object newValue)
     at Xenko.Core.Assets.Editor.Quantum.ViewModels.AssetNodeViewModel.SetNodeValue(Object newValue)
     at Xenko.Core.Presentation.Quantum.ViewModels.NodeViewModel.set_NodeValue(Object value)

  InnerException:
    InvalidOperationException: OnPropertyChanged called for property 'NodeValue' but OnPropertyChanging was not invoked before.
       at Xenko.Core.Presentation.ViewModel.ViewModelBase.OnPropertyChanged(String[] propertyNames)
       at Xenko.Core.Presentation.ViewModel.DispatcherViewModel.<>n__1(String[] propertyNames)
       at Xenko.Core.Presentation.ViewModel.DispatcherViewModel.<>c__DisplayClass5_0.<OnPropertyChanged>b__0()
       at Xenko.Core.Presentation.View.DispatcherService.Invoke(Action callback)
       at Xenko.Core.Presentation.ViewModel.DispatcherViewModel.OnPropertyChanged(String[] propertyNames)
       at Xenko.Core.Presentation.Quantum.ViewModels.NodeViewModel.OnPropertyChanged(String[] propertyNames)
       at Xenko.Core.Presentation.Quantum.ViewModels.NodeViewModel.OnValueChanged()
       at Xenko.Core.Presentation.Quantum.ViewModels.NodeViewModel.ValueChanged(Object sender, ValueChangedEventArgs valueChangedEventArgs)
       at Xenko.Core.Presentation.Quantum.Presenters.NodePresenterBase.RaiseValueChanged(Object oldValue)
       at Xenko.Core.Presentation.Quantum.Presenters.VirtualNodePresenter.RaiseNodeChanged(Object oldValue, ContentChangeType changeType, NodeIndex index)
       at Xenko.Core.Presentation.Quantum.Presenters.VirtualNodePresenter.UpdateValue(Object newValue)


```

**Comment by Basewq** [comment]
I've reproduced the issue, this is a debug mode only exception.
https://github.com/xenko3d/xenko/blob/9cb2785c80321467d9f2b234403834e1a7caa3c4/sources/presentation/Xenko.Core.Presentation/ViewModel/ViewModelBase.cs#L289-L294

Too complicated for me to understand how to fix. It has something to do with PropertyChanging/PropertyChanged events on some higher level, but PropertyChanging is registered multiple times somehow causing it to reach this issue.

However, this should really only be a `Debug.Assert` rather than throwing the exception, however this might imply there is some sort of underlying issue (though since it's working under release so maybe not too problematic)

**Comment by Eideren** [comment]
I mistakenly opened a duplicate (#2427) of this issue a while ago, but I'll close this one as the other has more information
