### ISSUE TITLE
MacOSX Exports fail: missing dependencies / DLLs

### ISSUE THREAD

**Issue by phr00t** [xenko3d/xenko#542]
**Release Type**: Github

**Version**: Latest (my Focus fork)

**Platform(s)**: Mac OSX

**Describe the bug**
All packages and DLLs for Xenko are not included when publishing to the Mac platform. Xenko.Graphics.dll seems to be missing, although others are there like Xenko.Rendering.dll

**To Reproduce**
1. Publish any Xenko project to the Mac OS platform
2. See the published output missing DLLs

**Expected behavior**
All DLLs and runtime files should be included for Mac OS to run properly.

**Log and callstacks**
macOSPublish phr00t$ ./GentrieveX.macOS 

Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Xenko.Graphics, Version=3.3.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at Xenko.Core.Serialization.AssemblyScan.Xenko_EngineAssemblyScan.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Xenko.Core.DataSerializers.GentrieveX_macOSSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
Abort trap: 6

**Comment by phr00t** [comment]
May be related to a merge I had trouble with on my fork, investigating...

**Comment by phr00t** [comment]
The merges that supposedly fixes this issue broke Linux building, reported here: https://github.com/xenko3d/xenko/issues/544

Hopefully when that issue gets resolved, this one will be resolved too. Closing for now.
