### ISSUE TITLE
Error building Xenko.Assets.Tests2 

### ISSUE THREAD

**Issue by gitfool** [xenko3d/xenko#69]
I'm consistently getting the following error building `Xenko.Assets.Tests2`:
```
74>------ Build started: Project: Xenko.Assets.Tests2, Configuration: Debug Any CPU ------
74>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "D:\Devel\Repos\Xenko\Bin\Windows\Xenko.Assimp.Translation.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
74>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "D:\Devel\Repos\Xenko\Bin\Windows\Xenko.Importer.Assimp.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
74>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "D:\Devel\Repos\Xenko\Bin\Windows\Xenko.Importer.Common.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
74>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "D:\Devel\Repos\Xenko\Bin\Windows\Xenko.Importer.FBX.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
74>Patch for assembly [Xenko.Assets.Tests2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
74>Xenko.Assets.Tests2 -> D:\Devel\Repos\Xenko\Bin\Windows\Tests\Xenko.Assets.Tests2\Xenko.Assets.Tests2.exe
74>info 0.000s: [AssetCompiler] BuildEngine arguments: --compile-property:SolutionDir=D:\Devel\Repos\Xenko\build\;SolutionName=Xenko;BuildProjectReferences=false --property:XenkoGraphicsApi=Direct3D11 --disable-auto-compile --project-configuration Debug --platform=Windows --profile=Windows --project-configuration=Debug --output-path=D:\Devel\Repos\Xenko\Bin\Windows\Tests\Xenko.Assets.Tests2\data --build-path=D:\Devel\Repos\Xenko\sources\engine\Xenko.Assets.Tests2\Cache\data --package-file=D:\Devel\Repos\Xenko\sources\engine\Xenko.Assets.Tests2\Xenko.Assets.Tests2.xkpkg --log-pipe=
74>info 0.000s: [AssetCompiler] Starting builder.
74>EXEC : error System.ServiceModel.CommunicationException: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.
74>
74>Server stack trace:
74>   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
74>   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
74>   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
74>
74>Exception rethrown at [0]:
74>   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
74>   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
74>   at Xenko.ExecServer.IExecServerRemote.Run(String currentDirectory, Dictionary`2 environmentVariables, String[] args, Boolean shadowCache, Nullable`1 debuggerProcessId)
74>   at Xenko.ExecServer.ExecServerApp.RunClient(String executablePath, String workingDirectory, Dictionary`2 environmentVariables, List`1 args, Boolean shadowCache, Nullable`1 debuggerProcessId)
74>RunTime 00:01:10.42
74>D:\Devel\Repos\Xenko\Targets\Xenko.targets(374,5): error MSB3073: The command ""D:\Devel\Repos\Xenko\Bin\Windows\Xenko.Core.Assets.CompilerClient.exe" --compile-property:SolutionDir=D:\Devel\Repos\Xenko\build\;SolutionName=Xenko;BuildProjectReferences=false --property:XenkoGraphicsApi=Direct3D11 --disable-auto-compile --project-configuration "Debug" --platform=Windows --profile=Windows --project-configuration=Debug --output-path="D:\Devel\Repos\Xenko\Bin\Windows\Tests\Xenko.Assets.Tests2\data" --build-path="D:\Devel\Repos\Xenko\sources\engine\Xenko.Assets.Tests2\Cache\data" --package-file="D:\Devel\Repos\Xenko\sources\engine\Xenko.Assets.Tests2\Xenko.Assets.Tests2.xkpkg" --log-pipe=""" exited with code -300.
74>Done building project "Xenko.Assets.Tests2.csproj" -- FAILED.
```
This interferes with running the unit tests since the build nearly always fails.

**Comment by gitfool** [comment]
Note: this always happens when I build the Xenko solution. If I then select the `Xenko.Assets.Tests2` project in the solution and build from there, it builds successfully.
