### ISSUE TITLE
some project files are not being generated

### ISSUE THREAD

**Issue by FastVisionGames** [xenko3d/xenko#91]
whenever I try to open any xenko project in visual studio I get these two warnings:

Warning	MSB3245	Could not resolve this reference. Could not locate the assembly "Xenko.Video". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	

Warning	The project 'ThirdPersonPlatformer3.Game' cannot be referenced.	

I have two targets for my project, both are missing some files:

The windows target is missing the Xenko video assembly.

The uwp target is missing project.json and ThirdPersonPlatformer3.UWP.TemporaryKey.pfx

Whenever I try to build the Windows version on the release configuration I don´t get any errors at all,
but when I try to build the uwp version on the same configuration i get the following errors:

Error: NUTC3059:Failed to find member with name 'Item2' and signature '6 13 1' in type '$ILT$FakeType1_System_ValueTuple`2<Xenko.Rendering.Materials.IMaterialShadingModelFeature, Xenko.Rendering.Materials.ShadingModelShaderBuilder>' while resolving token 'a0008f3' from module 'Xenko.Engine' while compiling method 'instance Xenko.Rendering.Materials.ShadingModelShaderBuilder Xenko.Rendering.Materials.MaterialGeneratorContext.GetShading<System.__Canon>(System.__Canon)'.	

Error Field 'ContainerFormatGuids.Bmp' was not included in compilation, but was referenced in method 'WICHelper.GetContainerFormatFromFileType(ImageFileType)'. There may have been a missing assembly.

Error Field 'ContainerFormatGuids.Bmp' was not included in compilation, but was referenced in method 'WICHelper.GetContainerFormatFromFileType(ImageFileType)'. There may have been a missing assembly.

Error Field 'ContainerFormatGuids.Gif' was not included in compilation, but was referenced in method 'WICHelper.GetContainerFormatFromFileType(ImageFileType)'. There may have been a missing assembly.

Error Field 'ContainerFormatGuids.Gif' was not included in compilation, but was referenced in method 'WICHelper.GetContainerFormatFromFileType(ImageFileType)'. There may have been a missing assembly.	

Error Field 'ContainerFormatGuids.Jpeg' was not included in compilation, but was referenced in method 'WICHelper.GetContainerFormatFromFileType(ImageFileType)'. There may have been a missing assembly.	

Warning	ILTransform : warning ILT0002: Field 'PixelFormat.Format32bppRGBA1010102' was not included in compilation, but was referenced in method 'WICHelper.DetermineFormat(Guid, WICFlags, Guid)'. There may have been a missing assembly.

Warning	ILTransform : warning ILT0005: Type 'SharpDX.MediaFoundation.ByteStream' was not included in compilation, but was referenced in type 'Xenko.Video.VideoInstance'. There may have been a missing assembly.	

Warning ILTransform : warning ILT0027: Invalid IL detected in method 'System.Void Xenko.Core.Storage.ObjectIdSimpleBuilder.Write<T>(T)' at IL offset 0x15.				

I reinstalled Xenko and Visual Studio multiple times and I still get the same errors.

Visual Studio details:
Version: Visual Studio Comunity 2017 15.7.6
Workloads: 
.NET desktop development
Desktop development with C++
Game development with C++
.NET Core cross-platform development
Mobile development with .NET
Universal Windows Platform development

side note: whenever I try to open a script in Xenko game studio
Xenko crashes
and gives out this error log
Application: GameStudio
UserEmail: 
UserMessage: 
XenkoVersion: 3.0.0.3
GameStudioVersion: 4
ThreadName: Main thread
DefaultGraphicProfile: Level_10_0
OpenedAssets: ec5013e5-04fd-4ceb-a1a8-11598242a728:MainScene (Scene)
b061dfb6-4c20-6714-2524-d1f61330d614:BasicCameraController (Script Source Code)

LastActions: 
CurrentDirectory: C:\Program Files\Xenko
CommandArgs: C:\Users\J\Documents\Xenko Projects\ThirdPersonPlatformer3\ThirdPersonPlatformer3.sln
OsVersion: Microsoft Windows 10 Home 10.0.17134 x64
ProcessorCount: 8
Exception: TaskCanceledException: Eine Aufgabe wurde abgebrochen.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<GetSyntaxRootAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.AbstractDirectiveTriviaBraceMatcher`5.<FindBracesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.BraceMatchingService.<GetMatchingBracesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RoslynPad.Roslyn.BraceMatching.BraceMatchingServiceExtensions.<GetAllMatchingBracesAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xenko.Assets.Presentation.AssetEditors.ScriptEditor.SimpleCodeTextEditor.<CaretOnPositionChanged>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xenko.GameStudio.Program.Main()

GPU0.AdapterCompatibility: Advanced Micro Devices, Inc.
GPU0.AdapterDACType: Internal DAC(400MHz)
GPU0.AdapterRAM: 2147483648
GPU0.Availability: 3
GPU0.Caption: ASUS R7 250X Series
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 3840
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 60
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 2160
GPU0.Description: ASUS R7 250X Series
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20170922000000.000000-000
GPU0.DriverVersion: 22.19.677.257
GPU0.InfFilename: oem12.inf
GPU0.InfSection: ati2mtag_R575ADS
GPU0.InstalledDisplayDrivers: C:\WINDOWS\System32\DriverStore\FileRepository\c0318486.inf_amd64_11ba0b4b7cc81d52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0318486.inf_amd64_11ba0b4b7cc81d52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0318486.inf_amd64_11ba0b4b7cc81d52\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\c0318486.inf_amd64_11ba0b4b7cc81d52\amdxc64.dll
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 30
GPU0.Monochrome: False
GPU0.Name: ASUS R7 250X Series
GPU0.PNPDeviceID: PCI\VEN_1002&DEV_683D&SUBSYS_300B1043&REV_00\4&3A986AA3&0&0010
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: DESKTOP-1HN0ABH
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 3840 x 2160 x 4294967296 Farben
GPU0.VideoProcessor: AMD Radeon Graphics Processor (0x683D)
Log:

**Comment by Aminator9000** [comment]
For UWP just remove project.json and TemporaryKey.pfx from your project as you don't need them. (Create a new certificate when you sideload on another machine.) Set the target and minimum version to the highest one you have installed. It still can't locate the assembly Xenko.Video, so that has to be fixed.
